### PR TITLE
Use scala-logging

### PR DESCRIPTION
**Pull request by atais**
should go after #38

### CODE REVIEW

**Comment by dyrkin** [comment]
hey. could you rebase this one onto the latest master?

**Comment by dyrkin** [comment]
and fix this error please https://cloud.drone.io/dyrkin/luxmed-bot/200/1/3

**Comment by atais** [comment]
sure thing. i pinged you on telegram as well :-)

btw. I think I broke the dockerfiles :/ damn I thought it is tested, just not pushed :(

**Comment by dyrkin** [comment]
yeah. we can extract the building of a docker image into a separate step like`build_docker_image`. publish will be responsible just for publishing

**Comment by atais** [comment]
now its ready :)

**Comment by dyrkin** [comment]
could you try to run your image? the bot currently isn't working
```
Aug 10 17:49:25 ubuntu docker-compose[22101]: luxmedbookingservice_1  | ./run.sh: 1: nc: not found
```

**Comment by dyrkin** [comment]
merging

**Pull request merged**
