### PR TITLE
Update Gradle build-tool

### PR DESCRIPTION
**Pull request by atais**
Its not much, but maybe a good start.

I would like to update some dependencies, fix log4shell and update java to 11/17

### CODE REVIEW

**Comment by dyrkin** [comment]
Hey. Thanks for the PR. It is very appreciated)
Could you fix this: https://cloud.drone.io/dyrkin/luxmed-bot/177/1/2? It is failing because of a missing JUnit dependency in the test scope? Not really sure.

**Comment by dyrkin** [comment]
And it seems you need to update the drone pipeline to use a different base image.

**Comment by atais** [comment]
Yes I cant update JDK yet because some libs need JDK 8 :/

And the test that fails is using JUnit (which I did not expect) and which is now disabled in favour of ScalaTest.
I wonder if we could stop using Spring and JUnit in the DB test....

I tried disabling the annotations yesterday but they are doing a lot of magic steps I cant execute manually :/

**Comment by atais** [comment]
well the spring is integrated heavily into the code so for now I left it as is

**Comment by atais** [comment]
we do you add kotlin runtime btw? I cant see usages

**Comment by atais** [comment]
we need to disable pushing image on MR's

**Comment by dyrkin** [comment]
i've got this error during an attempt to run it locally:
```
2022-08-09 15:47:32 o.s.o.j.LocalContainerEntityManagerFactoryBean - Initialized JPA EntityManagerFactory for persistence unit 'default'
2022-08-09 15:47:32 o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bootConfig': Unsatisfied dependency expressed through field 'apiService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'apiService': Unsatisfied dependency expressed through field 'textEncryptor'; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'bootConfig': Requested bean is currently in creation: Is there an unresolvable circular reference?
2022-08-09 15:47:32 o.s.o.j.LocalContainerEntityManagerFactoryBean - Closing JPA EntityManagerFactory for persistence unit 'default'
2022-08-09 15:47:32 c.z.h.HikariDataSource - HikariPool-1 - Shutdown initiated...
2022-08-09 15:47:32 c.z.h.HikariDataSource - HikariPool-1 - Shutdown completed.
2022-08-09 15:47:32 o.s.b.a.l.ConditionEvaluationReportLoggingListener - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-08-09 15:47:33 o.s.b.d.LoggingFailureAnalysisReporter - 

***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

┌─────┐
|  bootConfig (field private com.lbs.server.service.ApiService com.lbs.server.BootConfig.apiService)
↑     ↓
|  apiService (field private org.jasypt.util.text.TextEncryptor com.lbs.server.service.ApiService.textEncryptor)
└─────┘


Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.


Process finished with exit code 1
```

**Comment by atais** [comment]
because there are a circular dependency between those classes...
how did you get away with that is beyond my understanding, but it seems I bumped spring-boot version and that was the issue.

fixed

**Comment by atais** [comment]
sorry cant fix it all in one go, but it seems gradle 7 need newer plugin, so I had to enable the flag in spring.
i guess it was enabled by default in older versions.

later I can try to fix up this code...

**Comment by dyrkin** [comment]
Awesome! Thanks. It seems to be working now. 
Please squash commits into a single one, give it some meaningful comment, and I'll merge this to the master branch.

**Comment by atais** [comment]
can you squash them in the merge with GitHub? 
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

**Comment by dyrkin** [comment]
done. thanks man)

**Pull request merged**
